services:
  leadable:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: leadable
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Tokyo
    env_file: .env
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml

  ollama:
      image: ollama/ollama:0.3.12
      container_name: leadable-ollama
      environment:
        - TZ=Asia/Tokyo
      volumes:
        - type: bind
          source: .ollama
          target: /root/.ollama
      ports:
        - "11434:11434"
      restart: unless-stopped
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]

  frontend:
    container_name: leadable-webapp
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: yarn serve
    stdin_open: true
    tty: true
    env_file: .env
    environment:
      TZ: Asia/Tokyo
      PATH: /home/node/.yarn/bin:/home/node/.config/yarn/global/node_modules/.bin:$PATH
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: frontend
        target: /app

volumes:
  leadable:
  ollama:
  frontend:
